export { default as Login } from './Login';
export { default as Dashboard } from './Dashboard';
export { default as Main } from './Main';
export { default as BandMember } from './BandMember';
export { default as Socials } from './Socials';
export { default as AboutBand } from './AboutBand';
export { default as NewMember } from './NewMember';
export { default as NewSocial } from './NewSocial';
export { default as EditBand } from './EditBand';
